# Each entry: {"definition": "...", "answer": "..."}
PATTERNS = [
    {"definition": "Provides an interface for creating families of related or dependent objects without specifying their concrete classes.", "answer": "abstract factory"},
    {"definition": "Convert the interface of a class into another interface clients expect.", "answer": "adapter"},
    {"definition": "Decouple an abstraction from an implementation so the two can vary independently.", "answer": "bridge"},
    {"definition": "Separate the construction of a complex object from its representation so that the same construction process can create different representations.", "answer": "builder"},
    {"definition": "Avoid coupling the sender of a request to its receiver by giving more than one object a chance to handle the request.", "answer": "chain of responsibility"},
    {"definition": "Encapsulate a request as an object, thereby letting you parameterize clients with different requests, queue or log requests, and support undoable operations.", "answer": "command"},
    {"definition": "Compose objects into tree structures to represent part-whole hierarchies.", "answer": "composite"},
    {"definition": "Attach additional responsibilities to an object dynamically.", "answer": "decorator"},
    {"definition": "Provide a unified interface to a set of interfaces in a subsystem.", "answer": "facade"},
    {"definition": "Define an interface for creating an object, but let subclasses decide which class to instantiate.", "answer": "factory method"},
    {"definition": "Use sharing to support large numbers of fine-grained objects efficiently.", "answer": "flyweight"},
    {"definition": "Given a language, define a representation for its grammar along with an interpreter that uses the representation to interpret sentences in the language.", "answer": "interpreter"},
    {"definition": "Provide a way to access the elements of an aggregate object sequentially without exposing its underlying representation.", "answer": "iterator"},
    {"definition": "Define an object that encapsulates how a set of objects interact.", "answer": "mediator"},
    {"definition": "Without violating encapsulation, capture and externalize an object's internal state so that the object can be restored to this state later.", "answer": "memento"},
    {"definition": "Define a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically.", "answer": "observer"},
    {"definition": "Specify the kinds of objects to create using a prototypical instance, and create new objects by copying this prototype.", "answer": "prototype"},
    {"definition": "Provide a surrogate or placeholder for another object to control access to it.", "answer": "proxy"},
    {"definition": "Ensure a class only has one instance, and provide a global point of access to it.", "answer": "singleton"},
    {"definition": "Allow an object to alter its behavior when its internal state changes.", "answer": "state"},
    {"definition": "Define a family of algorithms, encapsulate each one, and make them interchangeable.", "answer": "strategy"},
    {"definition": "Define the skeleton of an algorithm in an operation, deferring some steps to subclasses.", "answer": "template method"},
    {"definition": "Represent an operation to be performed on the elements of an object structure.", "answer": "visitor"},
]
